services:
  - type: web
    name: control-escolar-backend
    env: python
    plan: free
    region: oregon
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn control_escolar_desit_api.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --access-logfile logs/gunicorn.log
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://control-escolar-webapp-final-dgvfqz05q-keisi-perezs-projects.vercel.app"
    healthCheckPath: /api/health/
    autoDeploy: true
